import {
  DollarSign,
  Heart,
  BarChart3,
  Globe,
  Clock,
  Wallet,
  Zap,
  Shield,
  Target,
  Cpu,
  TrendingUp,
  Users
} from "lucide-react";

export type Feature = {
  id: string;
  slug: string;
  icon: any;
  title: string;
  description: string;
  accent: string;
  detailedDescription: string;
  benefits: string[];
  howItWorks: string[];
};

export const features: Feature[] = [
  {
    id: "dynamic-price",
    slug: "dynamic-price-allocation",
    icon: DollarSign,
    title: "Dynamic Price Allocation",
    description: "AI-powered pricing that adapts to demand, time slots, and peak gym hours.",
    accent: "#a855f7",
    detailedDescription: "Our Dynamic Price Allocation system leverages advanced AI algorithms to analyze real-time demand and gym capacity. This ensures that users get the best value for their sessions while gym owners optimize their facility usage during off-peak and peak hours.",
    benefits: [
      "Cost-effective session rates during off-peak hours",
      "Better management of gym crowd flow",
      "Fair pricing based on real-time demand",
      "Increased accessibility for budget-conscious fitness enthusiasts"
    ],
    howItWorks: [
      "AI analyzes historical and real-time footfall data",
      "Pricing is adjusted dynamically based on current occupancy",
      "Users can view live rates on the FitFare app",
      "Book sessions instantly at the displayed price"
    ]
  },
  {
    id: "period-tracking",
    slug: "period-tracking-for-women",
    icon: Heart,
    title: "Period Tracking for Women",
    description: "Personalized workout and recovery plans aligned with each menstrual phase.",
    accent: "#3b82f6",
    detailedDescription: "Designed specifically for women, this feature integrates menstrual cycle tracking with fitness planning. It provides tailored recommendations for exercise intensity, nutrition, and recovery based on hormonal changes throughout the month.",
    benefits: [
      "Optimized performance by aligning workouts with hormonal phases",
      "Reduced risk of injury through phase-specific recovery",
      "Personalized nutritional advice for each cycle stage",
      "Better understanding of the body's natural rhythms"
    ],
    howItWorks: [
      "Log cycle start and end dates in the app",
      "Receive daily workout recommendations tailored to your current phase",
      "Get insights into energy levels and mood fluctuations",
      "Access a library of exercises suitable for each stage of the cycle"
    ]
  },
  {
    id: "professional-dashboard",
    slug: "professional-dashboard-for-club-owners",
    icon: BarChart3,
    title: "Professional Dashboard for Club Owners",
    description: "Advanced analytics, revenue insights, attendance trends, and member management tools.",
    accent: "#ec4899",
    detailedDescription: "A comprehensive management suite for gym and fitness club owners. The Professional Dashboard provides a bird's-eye view of business operations, from real-time attendance tracking to deep financial analytics and member engagement metrics.",
    benefits: [
      "Real-time visibility into club operations",
      "Data-driven insights to improve member retention",
      "Streamlined revenue and billing management",
      "Automated attendance and check-in systems"
    ],
    howItWorks: [
      "Integrate your club's existing systems with the FitFare API",
      "Access the dashboard from any device via a secure web portal",
      "Monitor live footfall and revenue streams",
      "Generate detailed reports for strategic planning"
    ]
  },
  {
    id: "multiple-clubs",
    slug: "access-to-multiple-clubs-across-cities",
    icon: Globe,
    title: "Access to Multiple Fitness Centers Across Cities",
    description: "Train anywhere with seamless check-ins across partnered gyms nationwide.",
    accent: "#06b6d4",
    detailedDescription: "Break free from the limitations of a single-gym membership. With FitFare, you gain access to a vast network of partner clubs across multiple cities. Whether you're traveling for work or on vacation, your fitness routine goes with you.",
    benefits: [
      "Flexibility to work out in different locations",
      "Consistency in fitness routine while traveling",
      "Access to a variety of equipments and class types",
      "Seamless check-in experience at all partner gyms"
    ],
    howItWorks: [
      "Search for partner gyms in your current location via the app",
      "View gym facilities, ratings, and available time slots",
      "Book a session at your chosen club",
      "Check in using a unique QR code generated by the app"
    ]
  },
  {
    id: "no-contracts",
    slug: "no-long-term-contracts",
    icon: Clock,
    title: "No Long-Term Contracts",
    description: "Complete flexibility with zero lock-ins, cancellation fees, or commitments.",
    accent: "#10b981",
    detailedDescription: "We believe in earning your loyalty every day, not through restrictive contracts. FitFare offers a contract-free experience, giving you the freedom to choose when, where, and how you want to train without any long-term commitments.",
    benefits: [
      "No upfront joining fees or security deposits",
      "Freedom to pause or stop anytime without penalties",
      "Only pay for the services you actually use",
      "Reduced financial stress and commitment anxiety"
    ],
    howItWorks: [
      "Download the app and create a free account",
      "Browse available clubs and services",
      "Choose a 'Pay-As-You-Go' or short-term pass",
      "Start training immediately without signing any long-term agreements"
    ]
  },
  {
    id: "pay-as-you-go",
    slug: "pay-as-you-go-pricing",
    icon: Wallet,
    title: "Pay-As-You-Go Pricing",
    description: "Pay only for sessions you attend — transparent billing with no hidden charges.",
    accent: "#eab308",
    detailedDescription: "Our Pay-As-You-Go model is designed for the modern, busy individual. Forget about paying for a month of gym access and only going twice. With FitFare, you only pay for the specific sessions you attend, making fitness truly affordable.",
    benefits: [
      "Significant cost savings for occasional gym-goers",
      "Transparent billing with no hidden costs",
      "Easy top-up and payment options through the app",
      "Full control over your fitness budget"
    ],
    howItWorks: [
      "Select the gym and session time you want to attend",
      "See the exact price for that specific session",
      "Complete the payment using your preferred method in the app",
      "Your session is confirmed and ready to go"
    ]
  }
];
